---
title: "ex_pipeline"
output: html_document
---

```{r}
library(brms)
library(bayesplot)
library(hbsae)
source("../../bsae/data_wrangling.R")

idaho_obs_full = idaho_obs_full %>%
  mutate(obs_biomass = obs_biomass^(1/3))
```

```{r}
files = list.files("../R/")
for (file in files) {
  source(paste0("../R/", file))
}

rm(file, files)
```

```{r}
compare_estimates = function(estimate1, estimate2, join_by) {
  colnames(estimate1)[colnames(estimate1) != join_by] = c("mean", "variance")
  estimate1 = estimate1 %>%
    pivot_longer(c("mean", "variance"), values_to = "estimate1")
  colnames(estimate2)[colnames(estimate2) != join_by] = c("mean", "variance")
  estimate2 = estimate2 %>%
    pivot_longer(c("mean", "variance"), values_to = "estimate2")
  estimates = left_join(estimate1, estimate2, by = c(join_by, "name"))
  
  estimates %>%
    ggplot(aes(estimate1, estimate2)) +
    geom_abline(color = "red") +
    geom_point() +
    theme_bw() +
    labs(title = "Comparison of point estimates",
         x = "First Estimate", y = "Second Estimate") +
    facet_wrap(~name, scale = "free") +
    theme(axis.title = element_blank()) %>%
    return()
}
```


```{r}
idaho_obs_no_zeroes = idaho_obs_full %>%
  filter(obs_biomass > 0)

pred_area = idaho_aux_full %>%
  group_by(county) %>%
  filter(county %in% idaho_obs_no_zeroes$county) %>%
  reframe(tcc = mean(tcc, na.rm = T),
          evc = mean(evc, na.rm = T),
          n = n()) %>%
  mutate(intercept = 1) %>%
  drop_na()

counties = pred_area$county
pred_area_sizes = pred_area$n

pred_area = as.matrix(pred_area[,c("intercept", "tcc", "evc")])
rownames(pred_area) = counties

hbsae_bhf = fSAE.Unit(
  y = idaho_obs_no_zeroes$obs_biomass,
  X = cbind(1, idaho_obs_no_zeroes$tcc, idaho_obs_no_zeroes$evc),
  area = idaho_obs_no_zeroes$county,
  Narea = pred_area_sizes,
  Xpop = pred_area,
  fpc = FALSE
)
hbsae_df = data.frame(
  county = names(hbsae_bhf$est),
  mean = hbsae_bhf$est,
  var = hbsae_bhf$mse
)
```

```{r}
fit_BHF = specify(
  model = "BHF",
  domain = "county",
  response = "obs_biomass",
  auxiliary_variables = c("tcc", "evc")
) %>%
  fit.basal_spec(
    data = (idaho_obs_full %>% filter(obs_biomass > 0))
  )

check_BHF = check.basal_fit(
  fit_BHF
) # posterior predictives will be bad but we are using this to compare to hbsae

estimates_BHF = estimate.basal_fit(
  fit = fit_BHF,
  newdata = idaho_aux_aggregate,
  domain = "county",
  ndraws = 5000,
); estimates_BHF$preds
```


```{r}
compare_estimates(estimates_BHF$preds, hbsae_df, "county")
```



```{r}
fit_custom = specify(
  formula = formula(obs_biomass ~ tcc + evc + (1 | county)),
  level = "unit"
) %>%  
  fit.basal_spec(
    .,
    (idaho_obs_full %>% filter(obs_biomass > 0))
  )

check_custom = check.basal_fit(
  fit = fit_custom
)

estimates_custom = estimate.basal_fit(
  fit = fit_custom,
  newdata = idaho_aux_aggregate,
  domain = "county",
  ndraws = 5000
); estimates_custom$preds
```

```{r}
compare_estimates(estimates_custom$preds, hbsae_df, "county")
```

```{r}
spec_FH = specify(
  model = "FH",
  domain = "county",
  response = "obs_biomass",
  auxiliary_variables = c("tcc", "evc")
)

fit_FH = fit.basal_spec(
  spec_FH,
  idaho_obs_full %>% filter(obs_biomass > 0),
  population_size = nrow(idaho_aux_full)
)

check_FH = check.basal_fit(
  fit = fit_FH,
  draws = 200
)

# we compare estimates with `hbsae` by re-estimating on the fitted data
estimates_FH = estimate.basal_fit(
  fit = fit_FH,
  newdata = fit_FH$data,
  domain = "county",
  ndraws = 5000
); estimates_FH$preds
```


```{r}
fh_hbsae = fSAE.Area(
  est.init = fit_FH$data$BASAL_HT_ESTIMATOR,
  var.init = fit_FH$data$BASAL_HT_SE^2,
  X = cbind(1, fit_FH$data$tcc, fit_FH$data$evc)
)

hbsae_fh_df = data.frame(
  county = fit_FH$data$county,
  mean = fh_hbsae$est,
  var = fh_hbsae$mse
)
```

```{r}
compare_estimates(estimates_FH$preds, hbsae_fh_df, "county")
```

```{r}
spec_area_custom = specify(
  formula = obs_biomass ~ tcc + evc + (1 | county),
  level = "area",
  domain = "county"
)

fit_area_custom = fit.basal_spec(
  spec_area_custom,
  idaho_obs_full %>% filter(obs_biomass > 0),
  population_size = nrow(idaho_aux_full)
)

check_area_custom = check.basal_fit(
  fit = fit_area_custom,
  draws = 200
)

# we compare estimates with `hbsae` by re-estimating on the fitted data
estimates_area_custom = estimate.basal_fit(
  fit = fit_area_custom,
  newdata = fit_area_custom$data,
  domain = "county",
  ndraws = 5000
); estimates_area_custom$preds
```

```{r}
compare_estimates(estimates_area_custom$preds, hbsae_fh_df, "county")
```

