---
title: "ex_pipeline"
output: html_document
---

```{r}
library(brms)
source("../../bsae/data_wrangling.R")
```

```{r}
files = list.files("../R/")
for (file in files) {
  source(paste0("../R/", file))
}

rm(file, files)
```


```{r}
spec_BHF = specify(
  model = "BHF",
  domain = "county",
  response = "obs_biomass",
  auxiliary_variables = c("tcc", "evc"),
  variable_transform = list(
    transform = function (y) {y^(1/3)},
    inv_transform = function (y) {y^3}
  )
)

fit_BHF = fit.basal_spec(
  spec_BHF, 
  (idaho_obs_full %>% filter(obs_biomass > 0))
)

check_BHF = check.basal_fit(
  fit = fit_BHF
)

estimates_BHF = estimate.basal_fit(
  fit = fit_BHF,
  newdata = idaho_aux_full,
  domain = "county",
  ndraws = 200
); estimates_BHF$preds
```

```{r}
spec_custom = specify(
  formula = formula(obs_biomass ~ tcc + evc + (1 | county)),
  level = "unit",
  variable_transform = list(
    transform = function (y) {y^(1/3)},
    inv_transform = function (y) {y^3}
  )
)

fit_custom = fit.basal_spec(
  spec_custom,
  (idaho_obs_full %>% filter(obs_biomass > 0))
)

check_custom = check.basal_fit(
  fit = fit_custom
)

estimates_custom = estimate.basal_fit(
  fit = fit_custom,
  newdata = idaho_aux_full,
  domain = "county",
  ndraws = 200
); estimates_custom$preds
```

```{r}
spec_FH = specify(
  model = "FH",
  domain = "county",
  response = "obs_biomass",
  auxiliary_variables = c("tcc", "evc"),
  variable_transform = list(
    transform = function (y) {y^(1/3)},
    inv_transform = function (y) {y^3}
  )
)

fit_FH = fit.basal_spec(
  spec_FH,
  idaho_obs_full %>% filter(obs_biomass > 0),
  population_size = nrow(idaho_aux_full)
)

check_FH = check.basal_fit(
  fit = fit_FH
)

estimates_FH = estimate.basal_fit(
  fit = fit_FH,
  newdata = idaho_aux_full,
  domain = "county"
); estimates_custom$preds
```

To do:
1. Compare BHFs to each other and to `hbsae`
2. Fix FH models
3. Allow user to specify priors
4. (maybe) implement generics like `predict()`, `posterior_predict()`, or `post_epred()`
  - would make things like posterior predictive checks for two-stage models and similar things much much easier
  - While we're at it, we could extend `summary()` to `fit.basal` class

